name: Download CSV Files

on:
  schedule:
    - cron: '0 0 * * 1'  # Runs at midnight UTC every Monday
  workflow_dispatch:      # This enables manual runs

jobs:
  download-csvs:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4  # Update to latest version

      # Download CSV files using PowerShell's Invoke-WebRequest
      - name: Download CSVs
        run: |
          mkdir -p WahJumps/Data/CSV

          # NA Data Centers
          Invoke-WebRequest -Uri "https://docs.google.com/spreadsheets/d/1DyOqqECaNuAEntBxwv2NQ7p5rTrC1tDN9hHpcI_PNs4/export?format=csv&gid=82382952" -OutFile "WahJumps/Data/CSV/aether_cleaned.csv"
          Invoke-WebRequest -Uri "https://docs.google.com/spreadsheets/d/1DyOqqECaNuAEntBxwv2NQ7p5rTrC1tDN9hHpcI_PNs4/export?format=csv&gid=1186977950" -OutFile "WahJumps/Data/CSV/primal_cleaned.csv"
          Invoke-WebRequest -Uri "https://docs.google.com/spreadsheets/d/1DyOqqECaNuAEntBxwv2NQ7p5rTrC1tDN9hHpcI_PNs4/export?format=csv&gid=350373672" -OutFile "WahJumps/Data/CSV/crystal_cleaned.csv"
          Invoke-WebRequest -Uri "https://docs.google.com/spreadsheets/d/1DyOqqECaNuAEntBxwv2NQ7p5rTrC1tDN9hHpcI_PNs4/export?format=csv&gid=1383994086" -OutFile "WahJumps/Data/CSV/dynamis_cleaned.csv"

          # EU Data Centers
          Invoke-WebRequest -Uri "https://docs.google.com/spreadsheets/d/1DyOqqECaNuAEntBxwv2NQ7p5rTrC1tDN9hHpcI_PNs4/export?format=csv&gid=1339692877" -OutFile "WahJumps/Data/CSV/chaos_cleaned.csv"
          Invoke-WebRequest -Uri "https://docs.google.com/spreadsheets/d/1DyOqqECaNuAEntBxwv2NQ7p5rTrC1tDN9hHpcI_PNs4/export?format=csv&gid=175977131" -OutFile "WahJumps/Data/CSV/light_cleaned.csv"

          # OCE Data Center
          Invoke-WebRequest -Uri "https://docs.google.com/spreadsheets/d/1DyOqqECaNuAEntBxwv2NQ7p5rTrC1tDN9hHpcI_PNs4/export?format=csv&gid=874557131" -OutFile "WahJumps/Data/CSV/materia_cleaned.csv"

          # JP Data Centers
          Invoke-WebRequest -Uri "https://docs.google.com/spreadsheets/d/1DyOqqECaNuAEntBxwv2NQ7p5rTrC1tDN9hHpcI_PNs4/export?format=csv&gid=1856583868" -OutFile "WahJumps/Data/CSV/elemental_cleaned.csv"
          Invoke-WebRequest -Uri "https://docs.google.com/spreadsheets/d/1DyOqqECaNuAEntBxwv2NQ7p5rTrC1tDN9hHpcI_PNs4/export?format=csv&gid=1822506732" -OutFile "WahJumps/Data/CSV/gaia_cleaned.csv"
          Invoke-WebRequest -Uri "https://docs.google.com/spreadsheets/d/1DyOqqECaNuAEntBxwv2NQ7p5rTrC1tDN9hHpcI_PNs4/export?format=csv&gid=1045300014" -OutFile "WahJumps/Data/CSV/mana_cleaned.csv"
          Invoke-WebRequest -Uri "https://docs.google.com/spreadsheets/d/1DyOqqECaNuAEntBxwv2NQ7p5rTrC1tDN9hHpcI_PNs4/export?format=csv&gid=1643199164" -OutFile "WahJumps/Data/CSV/meteor_cleaned.csv"

      # Upload the downloaded CSVs as an artifact
      - name: Upload CSVs
        uses: actions/upload-artifact@v4  # Update to the latest version
        with:
          name: WahJumpsCSVs
          path: WahJumps/Data/CSV  # Path where the CSVs are downloaded
